# Giovani Nascimento Pereira - 168609
# Carlos A.F.F. Carvalho - 


nn1: neuralNetwork1.py
	python3 neuralNetwork1.py small

nn1-full: neuralNetwork1.py
	python3 neuralNetwork1.py full

nn1-small: neuralNetwork1.py
	python3 neuralNetwork1.py small

nn1-medium: neuralNetwork1.py
	python3 neuralNetwork1.py 10000 5000 

clean-image: 
	rm -rf *.png